### ISSUE TITLE
Defining & Passing data in more complex data structures like List & Dictionary Objects

### ISSUE THREAD

**Issue by vishal-agg** [lucianopuccio/golem#51]
In case user needs to pass data in more complex data structures like lists,dictionary,tuples etc, how can it be defined & passed as parameters inside functions(actions)?

Example:
List of standard common labels across application pages , to be verified  so the list of those labels/objects can be passed around as arguments to functions  to verify .

**Comment by lucianopuccio** [comment]
I made some changes and now the steps can accept different type of vars like tuples, dicts, lists, ints and booleans. The values will not be cast to strings as before. It also works when storing values in the data file.

<img width="1063" alt="screen shot 2017-10-27 at 3 08 17 pm" src="https://user-images.githubusercontent.com/2257588/32118677-ee26316a-bb28-11e7-8c99-2168057369bc.png">

**Comment by r-roos** [comment]
@lucianopuccio can you still safe strings with this change in Data ? I am getting some odd behavior with this latest commit:

For instance , the following csv content for Data will result in an valueError when loading the testcase in the GUI:
csv content:

> H1,H3,H2
> AB,EF,CD

Error when trying to open this test case to edit it via the GUI:
`ValueError: malformed node or string: <_ast.Name object at 0x7f6a82bfd128>`

quoting the csv content like 'AB','EF,'CD' will make it load, BUT after saving the test case data is stored again without the single quotes

**Comment by lucianopuccio** [comment]
This is partially fixed now (0.3.1)

The issue with using csv is that every value is a string by default. So what Golem does is try to convert each cell value of the csv to another variable type and if it cannot, it falls back to string. So for instance, True without quotes will be converted to boolean, 123 without quotes will be converted to int, and so on. This is definitely not pythonic. 

A better solution would be to use JSON instead. Something like this:
```
[
  {
    "user": "user1",
    "some_array": [1, 2, 3],
    "some_bool": true
  },
  {
    "user": "user2",
    "some_array": [4, 5, 6],
    "some_bool": false
  }
]
```

Conversion from JSON to Python is pretty straightforward. 
A couple of caveats: in the test builder, in the data table, string values would require to be surrounded by quotes. Currently they do not require quotes, but this it not necessarily better. 
Second, each data set would need to define the names for each value, as apposed to the CSV where they were just defined in the fist row, and all the data sets would need to be consistent.

Another approach, store single test data inside the test file itself (as an array of dictionaries). This is because I don't see much value in keeping it in a separate file. Or at least it could be optional to use either way.

Let me know what you think, thanks

**Comment by vishal-agg** [comment]
I would suggest to keep it simple in that scenario and stick with the current functionality using CSV only for now.

**Comment by lucianopuccio** [comment]
I added the 'test_data' setting to define where should the test data be saved, setting it to 'csv' will work the way it was working before, setting it to 'infile' will store the data inside the test itself (as a list of dictionaries).
I think this can be closed for now. Thanks!

**Comment by lucianopuccio** [comment]
@NRfpneflfifcL so the import error was because the test file had invalid syntax? if that's the case it is expected. What can be improved is the logging so it is easier to debug. If that was not the case let me know.


Just in case. The infile data should be a dictionary or a list of dictionaries. each item in the list is considered a data set (the test will be run once per each data set) and in that case, all the test sets should have the same keys.

```
data = [
    {
        'username': 'username01',
        'password': 'password01'
    },
    {
        'username': 'username02',
        'password': 'password02'
    }
]

def test(data):
    # ...
    send_keys(some_element, data.username)
    send_keys(other_element, data.password)
```

If you have questions, feel free to ask here: https://gitter.im/golem-framework/golem

Have a good day!

**Comment by NRfpneflfifcL** [comment]
Yes, test had a line with relative import that caused an error in `import_module`. Improved logging will help a lot for such cases. Thank you!
